export const TUTOR_INFO_REQUEST = 'TUTOR_INFO_REQUEST';
export const TUTOR_INFO_SUCCESS = 'TUTOR_INFO_SUCCESS';
export const TUTOR_INFO_FAILURE = 'TUTOR_INFO_FAILURE';
export const TUTOR_LECTURES_REQUEST = 'TUTOR_LECTURES_REQUEST';
export const TUTOR_LECTURES_SUCCESS = 'TUTOR_LECTURES_SUCCESS';
export const TUTOR_LECTURES_FAILURE = 'TUTOR_LECTURES_FAILURE';
