export const ChipListData = [
  {id: 0, text: '강의'},
  {id: 1, text: '수업 방식'},
  {id: 2, text: '동네'},
  {id: 3, text: '레벨'},
];

export const CategoryData = [
  {id: 0, explain: '강의 종류', text: '개발'},
  {id: 1, explain: '언어', text: 'java'},
];

export const CardData = [
  {
    id: 0,
    stack: ['SQL', 'Python'],
    title: '취업이 빨라지는 ',
    tutor: '김하나',
    cost: '33,000',
    hashTag: ['# 회사 10년 근무', '# sw개발 및 품질 경력'],
    heart: 1995,
    reviewCount: '135',
  },
  {
    id: 1,
    stack: ['SQL', 'Python'],
    title: '취업이 빨라지는 개발 교육 첫단계',
    tutor: '김하나',
    cost: '33,000',
    hashTag: ['# 회사 10년 근무', '# sw개발 및 품질 경력'],
    heart: 1995,
    reviewCount: '135',
  },
  {
    id: 2,
    stack: ['SQL', 'Python'],
    title: '취업이 빨라지는 개발 교육 첫단계',
    tutor: '김하나',
    cost: '33,000',
    hashTag: ['# 회사 10년 근무', '# sw개발 및 품질 경력'],
    heart: 1995,
    reviewCount: '135',
  },
  {
    id: 3,
    stack: ['SQL', 'Python'],
    title: '취업이 빨라지는 개발 교육 첫단계',
    tutor: '김하나',
    cost: '33,000',
    hashTag: ['# 회사 10년 근무', '# sw개발 및 품질 경력'],
    heart: 1995,
    reviewCount: '135',
  },
  {
    id: 4,
    stack: ['SQL', 'Python'],
    title: '취업이 빨라지는 개발 교육 첫단계',
    tutor: '김하나',
    cost: '33,000',
    hashTag: ['# 회사 10년 근무', '# sw개발 및 품질 경력'],
    heart: 1995,
    reviewCount: '135',
  },
  {
    id: 5,
    stack: ['SQL', 'Python'],
    title: '취업이 빨라지는 개발 교육 첫단계',
    tutor: '김하나',
    cost: '33,000',
    hashTag: ['# 회사 10년 근무', '# sw개발 및 품질 경력'],
    heart: 1995,
    reviewCount: '135',
  },
  {
    id: 6,
    stack: ['SQL', 'Python'],
    title: '취업이 빨라지는 개발 교육 첫단계',
    tutor: '김하나',
    cost: '33,000',
    hashTag: ['# 회사 10년 근무', '# sw개발 및 품질 경력'],
    heart: 1995,
    reviewCount: '135',
  },
  {
    id: 7,
    stack: ['SQL', 'Python'],
    title: '취업이 빨라지는 개발 교육 첫단계',
    tutor: '김하나',
    cost: '33,000',
    hashTag: ['# 회사 10년 근무', '# sw개발 및 품질 경력'],
    heart: 1995,
    reviewCount: '135',
  },
  {
    id: 8,
    stack: ['SQL', 'Python'],
    title: '취업이 빨라지는 개발 교육 첫단계',
    tutor: '김하나',
    cost: '33,000',
    hashTag: ['# 회사 10년 근무', '# sw개발 및 품질 경력'],
    heart: 1995,
    reviewCount: '135',
  },
];

export default {ChipListData, CategoryData, CardData};
