export const Filter = [
  {id: 0, text: '전체', isSelected: true},
  {id: 1, text: '개발 언어', isSelected: false},
  {id: 2, text: '수업 방식', isSelected: false},
  {id: 3, text: '레벨', isSelected: false},
];

export const Card = [
  {
    id: 0,
    tag: ['무료', '그룹'],
    remote: ['ONLINE', 'OFFLINE'],
    title: '금융권 취업을 위한 데이터 분석 및 모델링 SQL, R, Python',
    tutor: '김하나',
    heart: 56,
    rating: 5,
    review: 28,
    discount: 20,
    price: '197,000',
  },
  {
    id: 1,
    tag: ['무료', '그룹'],
    remote: ['ONLINE', 'OFFLINE'],
    title: '금융권 취업을 위한 데이터 분석 및 모델링 SQL, R, Python',
    tutor: '김하나',
    heart: 56,
    rating: 5,
    review: 28,
    discount: 20,
    price: '197,000',
  },
  {
    id: 2,
    tag: ['무료', '그룹'],
    remote: ['ONLINE', 'OFFLINE'],
    title: '금융권 취업을 위한 데이터 분석 및 모델링 SQL, R, Python',
    tutor: '김하나',
    heart: 56,
    rating: 5,
    review: 28,
    discount: 20,
    price: '197,000',
  },
  {
    id: 3,
    tag: ['무료', '그룹'],
    remote: ['ONLINE', 'OFFLINE'],
    title: '금융권 취업을 위한 데이터 분석 및 모델링 SQL, R, Python',
    tutor: '김하나',
    heart: 56,
    rating: 5,
    review: 28,
    discount: 20,
    price: '197,000',
  },
  {
    id: 4,
    tag: ['무료', '그룹'],
    remote: ['ONLINE', 'OFFLINE'],
    title: '금융권 취업을 위한 데이터 분석 및 모델링 SQL, R, Python',
    tutor: '김하나',
    heart: 56,
    rating: 5,
    review: 28,
    discount: 20,
    price: '197,000',
  },
  {
    id: 5,
    tag: ['무료', '그룹'],
    remote: ['ONLINE', 'OFFLINE'],
    title: '금융권 취업을 위한 데이터 분석 및 모델링 SQL, R, Python',
    tutor: '김하나',
    heart: 56,
    rating: 5,
    review: 28,
    discount: 20,
    price: '197,000',
  },
  {
    id: 6,
    tag: ['무료', '그룹'],
    remote: ['ONLINE', 'OFFLINE'],
    title: '금융권 취업을 위한 데이터 분석 및 모델링 SQL, R, Python',
    tutor: '김하나',
    heart: 56,
    rating: 5,
    review: 28,
    discount: 20,
    price: '197,000',
  },
  {
    id: 7,
    tag: ['무료', '그룹'],
    remote: ['ONLINE', 'OFFLINE'],
    title: '금융권 취업을 위한 데이터 분석 및 모델링 SQL, R, Python',
    tutor: '김하나',
    heart: 56,
    rating: 5,
    review: 28,
    discount: 20,
    price: '197,000',
  },
  {
    id: 8,
    tag: ['무료', '그룹'],
    remote: ['ONLINE', 'OFFLINE'],
    title: '금융권 취업을 위한 데이터 분석 및 모델링 SQL, R, Python',
    tutor: '김하나',
    heart: 56,
    rating: 5,
    review: 28,
    discount: 20,
    price: '197,000',
  },
];

export const DifficultyData = [
  {id: 0, title: 'BASIC', text: '기초'},
  {id: 1, title: 'BEGINNER', text: '초급'},
  {id: 2, title: 'INTERMEDIATE', text: '중급'},
  {id: 3, title: 'ADVANCED', text: '고급'},
];

export const GroupData = [
  {id: 0, boolean: true, text: '그룹'},
  {id: 1, boolean: false, text: '개인'},
];

export default {Filter, Card, DifficultyData, GroupData};
